---
- name: Install nginx
  dnf:
    name:
      - nginx
    state: present

- name: Install php-fpm
  dnf:
    name:
      - php-fpm
    state: present

- name: Start nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Start php-fpm
  service:
    name: php-fpm
    enabled: yes
    state: started

