---
- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Run httpd
  service:
    name: httpd
    enabled: yes
    state: started

- name: permit traffic in default zone for http service
  firewalld:
    service: http
    permanent: yes
    state: enabled

